txmatching/utils/hla_system/compatibility_index.py

Do not check for number of hla_types in group Other

---

tests/utils/hla_system/test_code_parser.py
tests/web/public_api/test_public_patient_upload_data_validation.py
tests/web/test_patient_api.py
txmatching/database/db_migrations/0025.add-hla-code-processing-result-empty-group.sql
txmatching/utils/hla_system/hla_transformations/hla_code_processing_result_detail.py
txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py

Add parsin error in case there is typing for one of the basic group missing.

---

tests/utils/hla_system/test_code_parser.py
tests/web/public_api/test_public_patient_upload_data_validation.py
tests/web/test_patient_api.py
txmatching/data_transfer_objects/hla/parsing_error_dto.py
txmatching/data_transfer_objects/hla/parsing_error_swagger.py
txmatching/database/db_migrations/0026.rename-processing-result-detail-alter-parsing-error.sql
txmatching/database/sql_alchemy_schema.py
txmatching/patients/hla_functions.py
txmatching/utils/hla_system/hla_table.py
txmatching/utils/hla_system/hla_transformations/get_mfi_from_multiple_hla_codes.py
txmatching/utils/hla_system/hla_transformations/hla_code_processing_result.py
txmatching/utils/hla_system/hla_transformations/hla_transformations.py
txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
txmatching/utils/hla_system/hla_transformations/parsing_error.py
txmatching/utils/hla_system/hla_transformations/parsing_issue_detail.py
txmatching/utils/hla_system/hla_transformations/utils.py
txmatching/web/frontend/src/app/generated/model/parsingErrorGenerated.ts
txmatching/web/frontend/src/app/model/ParsingError.ts
txmatching/web/frontend/src/app/parsers/parsingError.parsers.ts
txmatching/web/frontend/src/app/services/alert/alert.service.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml
txmatching/web/swagger/swagger_public.json

Allow nullable columns in parsing error table

---

tests/utils/hla_system/test_code_parser.py
txmatching/utils/hla_system/hla_transformations/hla_code_processing_result_detail.py

Add severity split to different parsing issue types

---

README.md
local_testing_utilities/generate_swagger.py
tests/web/test_user_api.py
txmatching/auth/auth_management.py
txmatching/data_transfer_objects/users/user_dto.py
txmatching/data_transfer_objects/users/user_swagger.py
txmatching/database/services/app_user_management.py
txmatching/web/__init__.py
txmatching/web/api/user_api.py
txmatching/web/frontend/src/app/generated/model/models.ts
txmatching/web/frontend/src/app/generated/model/userRegistrationOutGenerated.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml
txmatching/web/swagger/swagger_public.json

Dulezite je pri review tohoto vyzkouset readme, jestli budete schopni udelat, co je tam popsano, pripadne mi rict, jak to readme doplnit.

Improve users

---

txmatching/web/frontend/src/app/components/patient-donor-detail/patient-donor-detail.component.html
txmatching/web/frontend/src/app/components/patient-donor-item/patient-donor-item.component.ts
txmatching/web/frontend/src/app/components/patient-pair-item/patient-pair-item.component.ts
txmatching/web/frontend/src/app/components/patient-pair/patient-pair.component.html
txmatching/web/frontend/src/app/components/patient-recipient-detail/patient-recipient-detail.component.html
txmatching/web/frontend/src/app/components/warning-overview/warning-overview.component.html
txmatching/web/frontend/src/app/components/warning-overview/warning-overview.component.ts
txmatching/web/frontend/src/app/components/warning-overview/warning-pill/warning-pill.component.html
txmatching/web/frontend/src/app/components/warning-overview/warning-pill/warning-pill.component.scss
txmatching/web/frontend/src/app/components/warning-overview/warning-pill/warning-pill.component.ts
txmatching/web/frontend/src/app/components/warning/warning.component.html
txmatching/web/frontend/src/app/components/warning/warning.component.scss
txmatching/web/frontend/src/app/components/warning/warning.component.ts
txmatching/web/frontend/src/app/helpers/messages.ts
txmatching/web/frontend/src/app/model/Donor.ts
txmatching/web/frontend/src/app/model/Patient.ts
txmatching/web/frontend/src/app/model/Recipient.ts
txmatching/web/frontend/src/app/parsers/donor.parsers.ts
txmatching/web/frontend/src/app/parsers/patient.parsers.ts
txmatching/web/frontend/src/app/parsers/recipient.parsers.ts

Puvodni PR
https://github.com/mild-blue/txmatching/pull/813

#629 show parsing errors in patients detail - updates after CR

---

tests/web/public_api/test_public_patient_upload_data_validation.py
tests/web/public_api/test_public_patient_upload_invalid_example_data.py
tests/web/public_api/test_public_patient_upload_valid_example_data.py
txmatching/data_transfer_objects/matchings/matching_dto.py
txmatching/patients/patient.py

Pacienti kteri maji jen warning maji byt normalne zahrnuti do parovani, coz ted nejsou

Fix ignoring patients with warnings.

---

local_testing_utilities/add-new-ikem-user.http
txmatching/web/api/user_api.py

Small fixes to improve user creation.
before the query was not working due to missing "
and the object sent back did not contain the info we need

Improve new user creation.

---

txmatching/data_transfer_objects/base_patient_swagger.py
txmatching/data_transfer_objects/hla/parsing_issue_dto.py
txmatching/data_transfer_objects/hla/parsing_issue_swagger.py
txmatching/data_transfer_objects/matchings/matching_swagger.py
txmatching/data_transfer_objects/patients/out_dtos/conversions.py
txmatching/data_transfer_objects/patients/out_dtos/donor_dto_out.py
txmatching/data_transfer_objects/patients/out_dtos/recipient_dto_out.py
txmatching/database/services/parsing_issue_service.py
txmatching/web/api/patient_api.py
txmatching/web/frontend/src/app/generated/model/allTransplantMessagesGenerated.ts
txmatching/web/frontend/src/app/generated/model/models.ts
txmatching/web/frontend/src/app/generated/model/parsingIssueConfirmationGenerated.ts
txmatching/web/frontend/src/app/generated/model/transplantWarningGenerated.ts
txmatching/web/frontend/src/app/parsers/patient.parsers.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml

Send also parsing issue id and confirmation attributes to FE

---

tests/web/test_patient_api.py
tests/web/test_swagger_endpoint.py
txmatching/database/services/parsing_issue_service.py

Only warning parsing issue can be confirmed

---

tests/utils/test_matching.py
tests/web/public_api/test_public_patient_upload_invalid_example_data.py
tests/web/test_error_handler.py
txmatching/auth/exceptions.py
txmatching/data_transfer_objects/patients/update_dtos/donor_update_dto.py
txmatching/data_transfer_objects/patients/update_dtos/recipient_update_dto.py
txmatching/data_transfer_objects/patients/upload_dtos/donor_upload_dto.py
txmatching/data_transfer_objects/patients/upload_dtos/hla_antibodies_upload_dto.py
txmatching/data_transfer_objects/patients/upload_dtos/recipient_upload_dto.py
txmatching/database/services/matching_service.py
txmatching/database/services/parsing_utils.py
txmatching/database/services/patient_service.py
txmatching/patients/patient.py
txmatching/utils/transplantation_warning.py
txmatching/web/error_handler.py
txmatching/web/frontend/src/app/components/donor-settings/donor-settings.component.ts
txmatching/web/frontend/src/app/components/recipient-settings/recipient-settings.component.html
txmatching/web/frontend/src/app/components/recipient-settings/recipient-settings.component.ts
txmatching/web/frontend/src/app/directives/validators/form.directive.ts

Better how transplant errors are shown in tranplant detail

---

tests/database/services/test_txm_event_service.py
tests/solvers/ilp_solver/test_ilp_solver.py
txmatching/auth/exceptions.py
txmatching/database/services/txm_event_service.py
txmatching/solvers/ilp_solver/solve_ilp.py
txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py
txmatching/utils/hla_system/compatibility_index.py
txmatching/web/error_handler.py

Improve errors shown on FE

---

tests/utils/hla_system/test_code_parser.py
tests/web/public_api/test_public_patient_upload_data_validation.py
tests/web/public_api/test_public_patient_upload_valid_example_data.py
txmatching/utils/hla_system/hla_transformations/get_mfi_from_multiple_hla_codes.py

Improve multiple mfis

---

tests/auth/user/test_sms_service.py
txmatching/auth/user/sms_service.py

* and set `SMS_SERVICE_URL=https://sms.ikem.cz/SendMessage` on production deployment
* (can not test, sorry)

Use post with new sms service

---

documentation/README.md

Hi, I think it's good to have better view of these Broad-Splits associations.

Add the table of more Broad-Splits associations to the documentation

---

.github/workflows/add-issue-to-project.yml
documentation/README.md

Improve documentation

---

tests/web/test_optimizer_api.py
txmatching/data_transfer_objects/optimizer/optimizer_in_swagger.py
txmatching/optimizer/optimizer_functions.py
txmatching/optimizer/optimizer_request_object.py
txmatching/optimizer/optimizer_return_object.py
txmatching/solvers/ilp_solver/ilp_solver.py
txmatching/solvers/solver_base.py
txmatching/web/api/optimizer_api.py
txmatching/web/frontend/src/app/generated/model/pairGenerated.ts
txmatching/web/frontend/src/app/generated/model/statisticsGenerated.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml
txmatching/web/swagger/swagger_public.json

Add functionality to optimizer module

---

tests/solvers/ilp_solver/test_ilp_solver.py
txmatching/solvers/ilp_solver/solve_ilp.py
txmatching/solvers/ilp_solver/txm_configuration_for_ilp.py

Recipient with multiple donors - config not working if one of these recipients set as required

---

tests/utils/test_dict_to_dataclass.py
txmatching/database/services/patient_service.py
txmatching/web/api/configuration_api.py

Optimization: replaced dacite.to_dict with my solution

---

tests/database/services/test_patient_service.py
tests/utils/test_dict_to_dataclass.py
txmatching/database/services/patient_service.py

Optimized dataclass creation

---

README.md

Update readme that TXM with M1 works

---

tests/utils/hla_system/test_code_parser.py
tests/utils/hla_system/test_crossmatch.py
txmatching/patients/hla_functions.py
txmatching/utils/hla_system/hla_crossmatch.py
txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py

Unify functions raising warning about number of antiboides and them being in high res above cutoff and function is type a

---

txmatching/data_transfer_objects/base_patient_swagger.py
txmatching/web/frontend/src/app/generated/model/hLAAntibodyInGenerated.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml
txmatching/web/swagger/swagger_public.json

Improve textation of swagger

---

tests/web/public_api/test_public_patient_upload_data_validation.py
tests/web/test_txm_event_api.py
txmatching/data_transfer_objects/patients/utils.py
txmatching/database/services/parsing_utils.py
txmatching/database/services/patient_upload_service.py
txmatching/utils/copy/copy_patients_from_event_to_event.py
txmatching/utils/export/export_txm_event.py

Copy patients between txm events not working

---

tests/auth/user/test_sms_service.py
txmatching/utils/hla_system/rel_dna_ser_parsing.py

Solve DeprecationWarning and FutureWarning

---

txmatching/patients/hla_model.py

Unify Antibody and Antigen

---

local_testing_utilities/generate_patients.py
local_testing_utilities/recompute-parsing.http
tests/utils/hla_system/test_code_parser.py
txmatching/utils/hla_system/hla_table.py
txmatching/utils/hla_system/hla_transformations/hla_transformations.py
txmatching/utils/hla_system/hla_transformations/parsing_issue_detail.py
txmatching/utils/hla_system/rel_dna_ser_exceptions.py

Add recompute parsing to http requests
Improve text in parsing issue detail.
Remove exceptions from exceptions file that are not longer needed.

Add test testing assumed serology works correctly.

---

documentation/README.md

Prihodit do readme vysvetlivky o hla antigenech

---

tests/utils/hla_system/test_code_parser.py
txmatching/utils/hla_system/hla_regexes.py
txmatching/utils/hla_system/hla_table.py
txmatching/utils/hla_system/hla_transformations/hla_transformations.py

Consistent naming high res vs standartized high res vs ultra

---

tests/utils/hla_system/test_code_parser.py
txmatching/database/services/patient_service.py
txmatching/patients/hla_model.py
txmatching/utils/hla_system/hla_transformations/hla_transformations.py
txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py

Better square bracket antibody parsing

---

README.md
tests/web/web_utils/test_logging_config.py
tests/web/web_utils/test_traceback_formatters.py
txmatching/web/__init__.py
txmatching/web/web_utils/logging_config.py
txmatching/web/web_utils/traceback_formatters.py

Improve loggin vol 2

---

tests/web/test_patient_api.py
txmatching/database/services/patient_upload_service.py
txmatching/database/sql_alchemy_schema.py
txmatching/web/api/patient_api.py

Poor mans solution for multiple donors

---

txmatching/utils/hla_system/compatibility_index.py

Check correctly count of DP DQ antigens

---

tests/utils/hla_system/test_crossmatch.py

`hla_antibodies_raw_list` is empty

---

txmatching/patients/hla_functions.py
txmatching/patients/hla_model.py
txmatching/utils/hla_system/hla_preparation_utils.py

Rozsirit informaci o pridani theoretical antibody

---

txmatching/data_transfer_objects/patients/patient_in_swagger.py
txmatching/web/api/patient_api.py
txmatching/web/frontend/src/app/components/list-item/list-item.interface.ts
txmatching/web/frontend/src/app/components/matching-detail/matching-detail.component.ts
txmatching/web/frontend/src/app/components/patient-pair-detail/patient-pair-detail.component.html
txmatching/web/frontend/src/app/components/patient-pair-detail/patient-pair-detail.component.scss
txmatching/web/frontend/src/app/components/patient-pair-detail/patient-pair-detail.component.ts
txmatching/web/frontend/src/app/generated/model/recipientCompatibilityInfoJsonGenerated.ts
txmatching/web/frontend/src/app/model/Recipient.ts
txmatching/web/frontend/src/app/model/RecipientCompatibilityInfo.ts
txmatching/web/frontend/src/app/model/RecipientDonorCompatibilityDetail.ts
txmatching/web/frontend/src/app/parsers/recipient.parsers.ts
txmatching/web/frontend/src/app/parsers/recipientCompatibilityInfo.parsers.ts
txmatching/web/frontend/src/app/services/configuration/configuration.service.ts
txmatching/web/frontend/src/app/services/patient/patient.service.ts
txmatching/web/frontend/src/app/services/report/report.service.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml

Show cpra and compatible donors in patients list FE

---

tests/database/services/test_configuration.py
txmatching/configuration/config_parameters.py

Updating some configuration fields doesnt create new config

---

tests/patients/test_cpra_calculation.py
tests/test_utilities/prepare_app_for_tests.py
tests/web/test_patient_api.py
txmatching/data_transfer_objects/patients/out_dtos/conversions.py
txmatching/data_transfer_objects/patients/out_dtos/recipient_dto_out.py
txmatching/data_transfer_objects/patients/patient_in_swagger.py
txmatching/database/services/report_service.py
txmatching/patients/recipient_compatibility.py
txmatching/utils/recipient_donor_compatibility.py
txmatching/web/api/patient_api.py
txmatching/web/api/report_api.py
txmatching/web/frontend/src/app/generated/model/recipientGenerated.ts
txmatching/web/frontend/src/app/pages/abstract-logged/abstract-logged.component.ts
txmatching/web/frontend/src/app/pages/home/home.component.ts
txmatching/web/frontend/src/app/services/patient/patient.service.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml

Optimize computation of compatible donors for recipient

---

Dockerfile

Doufám, že přežijeme bez INFO logů od gunicorn :)

Fix JQ log parisng on STG/PROD.

---

txmatching/utils/hla_system/hla_crossmatch.py

v kode bola chybna manipulacia so setom - vedelo by to potencialne hodit error, tieto zmeny to fixuju

fix: set modification

---

tests/database/services/test_report.py
tests/resources/sample_html_report.html
txmatching/database/services/report_service.py
txmatching/templates/report_includes/macros.html
txmatching/templates/report_includes/transplant_component.macro.html
txmatching/templates/report_includes/transplant_component.styles.html
txmatching/utils/hla_system/hla_crossmatch.py
txmatching/web/frontend/src/app/components/code/code.component.scss
txmatching/web/frontend/src/app/components/matching-transplant/matching-transplant.component.html
txmatching/web/frontend/src/app/components/matching-transplant/matching-transplant.component.ts
txmatching/web/frontend/src/styles/definitions/colors.scss

Closes #1195
modre = info o tom ze aha tu je theoretical
oranzove = pozor theoretical match
report s SMALL_DATA_FOLDER_THEORETICAL vyzera takto

feat: theoretical antibody ukazovat menej vyrazne

---

tests/web/test_do_crossmatch_api.py
txmatching/utils/hla_system/hla_transformations/hla_transformations_store.py
txmatching/web/api/crossmatch_api.py

Handle theoretical double antibodies equivalent to the some donors HLAs

---

documentation/README.md

Popsat v README, jak funguje crossmatch API pro kadaverózní dárce

---

tests/resources/crossmatch_api_big_data_input.json
tests/resources/crossmatch_api_big_data_output.json
tests/web/test_do_crossmatch_api.py
txmatching/web/api/crossmatch_api.py

Closes #1227 
Smazal jsem neschválně původní PR  #1231

Převádět na začátku do assumed jen pak kontrolovat frequent/infrequent

---

txmatching/data_transfer_objects/base_patient_swagger.py
txmatching/utils/hla_system/hla_crossmatch.py
txmatching/web/frontend/src/app/generated/model/crossmatchSummaryGenerated.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml

Send `details_and_issues` as codes in crossmatch api.

---

tests/web/test_cpra_calculation.py
tests/web/test_do_crossmatch_api.py
txmatching/data_transfer_objects/crossmatch/crossmatch_dto.py
txmatching/data_transfer_objects/crossmatch/crossmatch_in_swagger.py
txmatching/web/api/crossmatch_api.py
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml

Add intergration data for cpra and crossmatch endpoints.

---

local_testing_utilities/export-patients.http
local_testing_utilities/notebooks/export_austrian_data.ipynb
tests/web/test_cpra_calculation.py
txmatching/data_transfer_objects/crossmatch/crossmatch_dto.py
txmatching/data_transfer_objects/crossmatch/crossmatch_in_swagger.py
txmatching/patients/hla_functions.py
txmatching/patients/hla_model.py
txmatching/web/api/crossmatch_api.py
txmatching/web/frontend/src/app/generated/model/calculateCPRAOutputGenerated.ts
txmatching/web/frontend/src/app/generated/model/crossmatchInputGenerated.ts
txmatching/web/frontend/src/app/generated/model/crossmatchOutputGenerated.ts
txmatching/web/frontend/src/app/generated/model/hLAAntibodyForCPRAJsonGenerated.ts
txmatching/web/frontend/src/app/generated/model/models.ts
txmatching/web/swagger/swagger.json
txmatching/web/swagger/swagger.yaml

closes #1271 
plus krome nazvu jeste trosicku upravuju austrian ntb, ale to je mini, to neni potreba ani delat review. Ten test co jsem pridal ma schvalne hodne dat, abych vyzkousel nejaky realny priklad..

Obohatit cpra endpoint o data ktery byly poslany do kalklatoru
